# Form implementation generated from reading ui file 'supawacky.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.setEnabled(True)
        Widget.resize(1205, 970)
        font = QtGui.QFont()
        font.setPointSize(15)
        Widget.setFont(font)
        self.TADW = QtWidgets.QLabel(parent=Widget)
        self.TADW.setGeometry(QtCore.QRect(0, 0, 1221, 971))
        self.TADW.setMinimumSize(QtCore.QSize(1221, 971))
        self.TADW.setMaximumSize(QtCore.QSize(1221, 971))
        self.TADW.setText("")
        self.TADW.setPixmap(QtGui.QPixmap("../The_WackyWatch_HQ.jpg"))
        self.TADW.setObjectName("TADW")
        self.TimedDisplay = QtWidgets.QLabel(parent=Widget)
        self.TimedDisplay.setGeometry(QtCore.QRect(300, 260, 151, 41))
        self.TimedDisplay.setScaledContents(False)
        self.TimedDisplay.setIndent(12)
        self.TimedDisplay.setObjectName("TimedDisplay")
        self.Confirm = QtWidgets.QPushButton(parent=Widget)
        self.Confirm.setGeometry(QtCore.QRect(900, 160, 91, 91))
        self.Confirm.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"} ")
        self.Confirm.setText("")
        self.Confirm.setObjectName("Confirm")
        self.Yes = QtWidgets.QPushButton(parent=Widget)
        self.Yes.setGeometry(QtCore.QRect(950, 280, 61, 61))
        self.Yes.setStyleSheet("QPushButton { \n"
"background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"}")
        self.Yes.setText("")
        self.Yes.setObjectName("Yes")
        self.N = QtWidgets.QPushButton(parent=Widget)
        self.N.setGeometry(QtCore.QRect(950, 380, 61, 61))
        self.N.setStyleSheet("QPushButton { \n"
"background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"}")
        self.N.setText("")
        self.N.setObjectName("N")
        self.NextButton = QtWidgets.QPushButton(parent=Widget)
        self.NextButton.setGeometry(QtCore.QRect(200, 620, 91, 91))
        self.NextButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"} ")
        self.NextButton.setText("")
        self.NextButton.setObjectName("NextButton")
        self.PP = QtWidgets.QLabel(parent=Widget)
        self.PP.setGeometry(QtCore.QRect(740, 270, 151, 20))
        self.PP.setText("")
        self.PP.setObjectName("PP")
        self.YOURNAME = QtWidgets.QLineEdit(parent=Widget)
        self.YOURNAME.setGeometry(QtCore.QRect(480, 500, 241, 41))
        self.YOURNAME.setStyleSheet("line edit {rgb(255, 255, 255)}")
        self.YOURNAME.setObjectName("YOURNAME")
        self.Question = QtWidgets.QLabel(parent=Widget)
        self.Question.setGeometry(QtCore.QRect(500, 450, 211, 31))
        self.Question.setObjectName("Question")
        self.Dialogue = QtWidgets.QLabel(parent=Widget)
        self.Dialogue.setGeometry(QtCore.QRect(450, 360, 281, 81))
        self.Dialogue.setStyleSheet("QPushButton {\n"
"border-image: url(:/images/);\n"
"background-color: transparent;\n"
"border: none;\n"
"}\n"
"")
        self.Dialogue.setText("")
        self.Dialogue.setIndent(90)
        self.Dialogue.setObjectName("Dialogue")
        self.Vid1 = QtWidgets.QPushButton(parent=Widget)
        self.Vid1.setGeometry(QtCore.QRect(390, 338, 90, 61))
        self.Vid1.setObjectName("Vid1")
        self.Vid2 = QtWidgets.QPushButton(parent=Widget)
        self.Vid2.setGeometry(QtCore.QRect(560, 340, 90, 61))
        self.Vid2.setObjectName("Vid2")
        self.Vid3 = QtWidgets.QPushButton(parent=Widget)
        self.Vid3.setGeometry(QtCore.QRect(730, 338, 90, 61))
        self.Vid3.setObjectName("Vid3")
        self.VideoContainer = QtWidgets.QWidget(parent=Widget)
        self.VideoContainer.setGeometry(QtCore.QRect(290, 230, 621, 441))
        self.VideoContainer.setObjectName("VideoContainer")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.TimedDisplay.setText(_translate("Widget", "00:00:00"))
        self.Question.setText(_translate("Widget", "Enter Your Name!"))
        self.Vid1.setText(_translate("Widget", "VIDEO"))
        self.Vid2.setText(_translate("Widget", "VIDEO?"))
        self.Vid3.setText(_translate("Widget", "VIDEO..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec())
